config/routes.rb
Rails.application.routes.draw do
  #  root to: "devise/sessions#create"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/hosts/auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  devise_for :hosts, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  #devise_for :hosts, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  #devise_for :hosts, :controllers => { :registration => "registration",
  #  :omniauth_callbacks => "omniauth_callbacks" }

  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hosts do
    resources :accomodations do
      resources :accomodation_photos
    end
  end

  require "resque_web"
    mount ResqueWeb::Engine => "/resque_web"
end

app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
  belongs_to :host
  has_many :accomodation_photos
  paginates_per 2

  validates :status, inclusion: { in: ["occupied", "unbooked"] }

  def self.with_hosts
    includes(:host).order("name")
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
  include RenderJson

  skip_before_action :verify_authenticity_token
  before_action :accomodation_params, only: [:create]
  before_action :get_host_id, only: [:create, :edit]
  before_action :find_accomodation_by_id
  before_action :ensure_that_accomodation_id_exists, only: [:destroy]

  def index
    #binding.pry
    #@accomodations = Accomodation.with_hosts.page(params[:page]).per(2)
    #@accomodations2 = Accomodation.order("name").page(params[:page]).per(2).to_sql
    #binding.pry
    @accomodations = Host.find(accomodation_params[:host_id]).accomodations.page(params[:page]).per(2)

  end

  def create
    new_accomodation = Accomodation.create(accomodation_params)
    render_json(new_accomodation)
    if new_accomodation.save
      Resque.enqueue(EmailHost, new_accomodation.id)
    end
  end

  def edit
    @accomodation.update_attributes(accomodation_params)
    render_json(@accomodation)
  end

  def destroy
    deleted_host = @found_accomodation_id.destroy
    render_json(deleted_host)
  end

  def search
    @searched_accomodation = Host.find(accomodation_params[:host_id]).accomodations.search(params[:search])
  end

  private

  def accomodation_params
    params.permit(:name, :location, :description, :status, :host_id)
  end

  def get_host_id
    accomodation_params[:host_id] = @host
  end

  def find_accomodation_by_id
    @accomodation = Accomodation.find_by(id: params[:id])
  end

  def ensure_that_accomodation_id_exists
    @found_accomodation_id ||= Accomodation.find_by(id: params[:id])
    unless @found_accomodation_id
      render json: {message: "Accomodation Id doesn't exist"}
    end
  end
end

app/views/accomodations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hosts</h1>
<div class="row">
  <div class="col-md-5">
    <%= form_tag(host_accomodations_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
    <%= submit_tag "Search" %>
    <% end %>

<table class="table table-striped">
 <thead>
   <tr>
     <th>Name</th>
     <th>Location</th>
     <th>Description</th>
     <th>Status</th>
     <th>Owner</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @accomodations.each do |accomodation| %>
   <% if @accomodation.present? %>
     <tr>
       <td><%= accomodation.name %></td>
       <td><%= accomodation.location %></td>
       <td><%= accomodation.description %></td>
       <td><%= accomodation.status %></td>
       <td><%= accomodation.host.email%></td>
     </tr>
     <% else %>
       <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
     <% end %>
   <% end %>
 </tbody>
</table>
</div>
</div>

<br>

<%= paginate @accomodations %>