config/routes.rb
Rails.application.routes.draw do
  #  root to: "devise/sessions#create"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/hosts/auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  devise_for :hosts, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  #devise_for :hosts, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  #devise_for :hosts, :controllers => { :registration => "registration",
  #  :omniauth_callbacks => "omniauth_callbacks" }

  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hosts do
    resources :accomodations do
      resources :accomodation_photos
    end
  end

  require "resque_web"
    mount ResqueWeb::Engine => "/resque_web"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !host_signed_in? %>
      <p class="sign_in"><%= link_to "Login", hosts_path %> </p>
      <%= link_to "Login with Facebook", host_facebook_omniauth_authorize_path, id: "log_in" %>
    <% end %>

    <% if host_signed_in? %>
      <div class="buttons">
        <button class="button"><%= link_to('Logout', destroy_host_session_path, :method => :delete) %></button>
      </div>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>