config/routes.rb
Rails.application.routes.draw do
  #  root to: "devise/sessions#create"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/hosts/auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  devise_for :hosts, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  #devise_for :hosts, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  #devise_for :hosts, :controllers => { :registration => "registration",
  #  :omniauth_callbacks => "omniauth_callbacks" }

  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hosts do
    resources :accomodations do
      resources :accomodation_photos
    end
  end

  require "resque_web"
    mount ResqueWeb::Engine => "/resque_web"
end

app/models/accomodation_photo.rb
class AccomodationPhoto < ActiveRecord::Base
  belongs_to :accomodation
  #validates :image_url, presence: true
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_attachment :photo, :presence => true,
  :content_type => { :content_type => "image/jpeg" },
  :size => { :in => 0..100.kilobytes }
end

app/controllers/accomodation_photos_controller.rb
class AccomodationPhotosController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :accomodation_photo_params, only: [:get_accomodation_id]
  before_action :get_accomodation_id, only: [:create]
  before_action :filter_accomodation_params, only: [:accomodation_params]

  def index
   @accomodation_photos = AccomodationPhoto.order('created_at')
 end

 def new
   @accomodation_photo = AccomodationPhoto.new
 end

 def create

   @accomodation_photo = AccomodationPhoto.new(
    photo: params[:accomodation_photo],
    accomodation_id: 1
   )
  #  binding.pry
   if @accomodation_photo.save
     flash[:success] = "The photo was added!"
     redirect_to root_path
   else
     render 'new'
   end
 end

 private

 def accomodation_photo_params
   params.permit(:image_url, :photo_file_name, :photo_content_type,
   :photo_file_size, :accomodation_id)
 end


#Unpermitted parameters: utf8, authenticity_token, accomodation_photo, commit, host_id
 def get_accomodation_id
   accomodation_photo_params[:accomodation_id] = @accomodation
 end

 # def filter_accomodation_params
 #   params.except(:utf8, :authenticity_token, :accomodation_photo, :commit, :host_id)
 # end
  # before_action :ensure_that_accomodation_photo_id_exists, only: [:destroy]
  # before_action :accomodation_photo_params, only: [:get_accomodation_id]
  # before_action :get_accomodation_id, only: [:create]
  #
  # def index
  #   @accomodation_photos = AccomodationPhoto.all
  # end
  #
  # def new
  #   @accomodation_photo = AccomodationPhoto.new
  # end
  #
  # def create
  #   new_accomodation_photo = AccomodationPhoto.create(accomodation_photo_params)
  #   render_json(new_accomodation_photo)
  # end
  #
  # def destroy
  #   deleted_accomodation_photo = @found_accomodation_photo_id.destroy
  #
  #   if deleted_accomodation_photo
  #     render json: { message: "Accomodation Photo Deleted"}
  #   end
  # end
  #
  # private
  #
  # def accomodation_photo_params
  #   params.permit(:image_url, :caption, :accomodation_id, :photo)
  # end
  #
  # def get_accomodation_id
  #   accomodation_photo_params[:accomodation_id] = @accomodation
  # end
  #
  # def ensure_that_accomodation_photo_id_exists
  #   @found_accomodation_photo_id ||= AccomodationPhoto.find_by(id: params[:id])
  #   unless @found_accomodation_photo_id
  #     render json: {message: "Accomodation Photo Id doesn't exist"}
  #   end
  # end
end

app/views/accomodation_photos/create.html.erb
<%= form_for @accomodation_photo, url: new_host_accomodation_accomodation_photo_path , html: { multipart: true } do |form| %>
  <%= form.file_field :photo %>
  <li><%= link_to 'Upload Your Photo', new_host_accomodation_accomodation_photo_path %></li>
<% end %>

app/views/accomodation_photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<%= @accomodation_photos.each do |accomodation_photo| %>
<%= image_tag(accomodation_photo.photo.url) %>
<% end %>

app/views/accomodation_photos/new.html.erb
<%= form_tag host_accomodation_accomodation_photos_path, :multipart => true do%>
Photo: <%= file_field_tag :accomodation_photo %>
<%= submit_tag "Save changes" %>
<% end %>


<!-- <div class="page-header"><h1>Upload Photo</h1></div>
<%= form_for @accomodation_photo, url: host_accomodation_accomodation_photos_path, method: :post , html: { multipart: true} do |form| %>
  <%= form.file_field :wew %>
  <%= form.submit 'Upload', class: 'btn btn-primary'%>
<% end %> -->


<!-- <div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @accomodation_photo, url: host_accomodation_accomodation_photos_path do |f| %>

  <div class="form-group">
    <%= f.label :accomodation_photo %>
    <%= f.file_field :accomodation_photo, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %> -->